<script setup>
import { useRideStore } from '@/stores/store';

const store = useRideStore();

async function generateSheet() {
    // see if can refactor this
    fetch("template.xlsx").then(res => {
        res.arrayBuffer().then(data => {
            fetch("logo.png").then(res => {
                res.arrayBuffer().then(imgData => {
                    let generated = window.myBundle(store.rides, store.total_pax, store.breakdown, data, imgData);
                    generated.then(async (result) => {
                        const blob = new Blob([result], { type: 'application/octet-stream' })
                        let date = new Date();
                        let fileName = `SH CABIN MANIFEST ${String(date.toLocaleDateString()).replaceAll("/","")} - autogenerated.xlsx`

                        const supportsFileSystemAccess =
                            'showSaveFilePicker' in window &&
                            (() => {
                                try {
                                    return window.self === window.top;
                                } catch {
                                    return false;
                                }
                            })();
                        // If the File System Access API is supported…
                        if (supportsFileSystemAccess) {
                            try {
                                // Show the file save dialog.
                                const handle = await showSaveFilePicker({
                                    suggestedName: fileName,
                                });
                                // Write the blob to the file.
                                const writable = await handle.createWritable();
                                await writable.write(blob);
                                await writable.close();
                                return;
                            } catch (err) {
                                // Fail silently if the user has simply canceled the dialog.
                                if (err.name !== 'AbortError') {
                                    console.error(err.name, err.message);
                                    return;
                                }
                            }
                        } else {
                            const link = document.createElement('a')
                            link.href = URL.createObjectURL(blob);
                            link.download = fileName;
                            link.click();
                            URL.revokeObjectURL(link.href);
                        }
                    })
                })
            })
        });
    });
}
</script>

<template>
    <div>
        <button id="generate" @click="generateSheet">
            <div>
                <span>Generate Excel Sheet (WIP)</span>
            </div>
        </button>
    </div>
    <div class="pax">
        Breakdown
        <table>
            <thead>
                <td>Nationality</td>
                <td>Adults</td>
                <td>Kids</td>
                <td>Total</td>
            </thead>
            <tbody>
                <tr v-for="(natl) in Object.entries(store.breakdown)" :key="natl">
                    <td>{{ natl[0] }}</td>
                    <td>{{ natl[1]["A"] }}</td>
                    <td>{{ natl[1]["K"] }}</td>
                    <td>{{ natl[1]["K"] + natl[1]["A"] }}</td>
                </tr>
                <tr>
                    <td>TOTAL</td>
                    <td></td>
                    <td></td>
                    <td>{{ store.total_pax }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

<style scoped>
div {
    text-align: center;
}

button {
    margin: auto;
    margin-top: 40px;
    border-radius: 5px;
    height: 50px;
    width: 80vw;
    max-width: 350px;
    padding: 0;
    border: 0;
    font-size: 23px;
    cursor: pointer;
    display: block;
    background-color: var(--secondary-color);
    box-shadow: 0px 5px rgba(0, 0, 0, 0.25);
}

form{
    margin-top:40px;
    color:white;
    max-width: 350px;
    text-align: left;
    margin:auto;
}
form label{
    margin-right:20px;
}
table {
    margin: auto;
    color: black;
}

td,
th {
    padding: 8px;
}

thead {
    background-color: white;
}

tr {
    background-color: white;
}

tr:nth-child(even) {
    background-color: #dddddd;
}

.pax {
    color: white;
    margin-top: 20px;
}

/* #generate > div > span {
    vertical-align: middle;
    margin-left:10px;
}
#generate > div > img {
    width:40px;
    height:40px;
    vertical-align: middle;
    position:relative;
    top:1px;
} */
</style>